server:
  contextPath: /api
  port: 8080

spring:
  application:
    name: ecommerceapp
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddlAuto: update
    databasePlatform: org.hibernate.dialect.MySQL8Dialect
  data:
    jpa:
      repositories:
        enabled: true
      showSql: true

